{% raw %}
name: Tests

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:
  pull_request:
    branches-ignore: []
  schedule:
    - cron: '0 0 8 * *'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python: [3.8, 3.9, '3.10']
      fail-fast: false


    steps:

    - name: install graphviz
      run: |
        sudo apt-get install -y graphviz

    - name: checkout git repo
      uses: actions/checkout@v2

    - name: conda/mamba
      uses: mamba-org/provision-with-micromamba@main
      with:
          environment-file: environment.yml
          extra-specs: |
            python=${{ matrix.python }}

    - name: install package itself
      shell: bash -l {0}
      run: |
        pip install .

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        pip install coveralls pytest-cov pytest pytest-xdist

    - name: testing
      shell: bash -l {0}
      run: |
        pytest -v --cov-report term-missing --cov=sequana_pipelines.{{cookiecutter.name}}

    - name: coveralls
      shell: bash -l {0}
      run: |
        echo $COVERALLS_REPO_TOKEN
        coveralls --service=github
      env:
          GITHUB_TOKEN: ${{ github.token }}
{% endraw %}

