# Schema validator for the quality_control
# author: Thomas Cokelaer

type: map
mapping:
    "sequana_wrappers":
        type: str
    "input_directory":
        type: str
        required: False
    "input_readtag":
        type: str
        required: False
    "input_pattern":
        type: str
        required: False
